server:
  port: 8091
  servlet:
    context-path: /databasepertenant
spring:
  application:
    name: databasepertenant
  jmx:
    default-domain: MultiTenancy
  flyway:
    enabled: false 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    properties:
      release_mode: after_transaction
      agressive_release: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
#    type : com.zaxxer.hikari.HikariDataSource
#    # Oracle DB
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SPRINGLEARN
    password: SPRINGLEARN
    hikari:
       minimum-idle : 5
       maximum-pool-size : 20
       idle-timeout : 30000
       pool-name : MULTITENANCY-CP
       #If there are more than minimumIdle number of connections the housekeeper will close connections that have been idle for longer than idleTimeout
       max-lifetime : 2000000
       connection-timeout : 30000
logging:
  level:
    com.zaxxer.hikari.HikariConfig : error
